# Generated by Django 3.0.6 on 2020-06-01 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200531_2253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
